name: inception

networks:
  inception:
    name: inception

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind
  mariadb:
    name: mariadb
    driver_opts:
      type: none
      device: ${HOME}/data/mariadb
      o: bind

secrets:
  db_password:
    file: ../secrets/db_password
  db_root_password:
    file: ../secrets/db_root_password
  domain.key:
    file: ../secrets/domain.key
  domain.crt:
    file: ../secrets/domain.crt
  wp_root_user_password:
    file: ../secrets/wp_root_user_password
  wp_user_password:
    file: ../secrets/wp_user_password
  
services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/${DOMAIN_NAME}/html
    secrets:
      - domain.key
      - domain.crt
    networks:
      - inception
    restart: always
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - mariadb
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - WP_TITLE=${WP_TITLE}
      - WP_ROOT_USER=${WP_ROOT_USER}
      - WP_ROOT_EMAIL=${WP_ROOT_EMAIL}
      - WP_USER=${WP_USER}
      - WP_EMAIL=${WP_EMAIL}
    volumes:
      - wordpress:/var/www/${DOMAIN_NAME}/html
    secrets:
      - db_password
      - wp_root_user_password
      - wp_user_password
    networks:
      - inception
    restart: always
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
      secrets:
        - db_password
        - db_root_password
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
